source 'ssh://gerrit.nexstreaming.com:29418/NexPods'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NexEditorSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NexEditorSample
  
  #pod 'NexEditorEngine', '~> 1.5.4'
  # For Development Pod build test
  pod 'NexEditorEngine', :path=> '../../../..'

  target 'NexEditorSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
