source 'https://github.com/KineMasterCorp/NexPods.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'APIDemos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIDemos
  pod 'NexEditorFramework', :path => '../../'
  # pod 'AssetReader', :path => '../../NexEditorFramework/AssetReader'
  # pod 'NexEditorEngine', :path => '../../../../NexEditor'
  pod 'SampleClipSources', :path=> '../../SampleClipSources'
  pod 'NexEditorEngine'

  target 'APIDemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APIDemosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
