/******************************************************************************
* File Name   :	NEXVIDEOEDITOR_Error.h
* Description :	
*******************************************************************************

Nextreaming Confidential Proprietary
Copyright (C) 2006 Nextreaming Corporation
All rights are reserved by Nextreaming Corporation

Revision History:
Author	Date		Description of Changes
-------------------------------------------------------------------------------
cskb		2011/07/25	Draft.
-----------------------------------------------------------------------------*/

//---------------------------------------------------------------------------
#ifndef _NEXVIDEOEDITOR_ERROR__H_
#define _NEXVIDEOEDITOR_ERROR__H_
//---------------------------------------------------------------------------

typedef enum _NEXVIDEOEDITOR_ERROR
{
	NEXVIDEOEDITOR_ERROR_NONE = 0,
	NEXVIDEOEDITOR_ERROR_GENERAL,
	NEXVIDEOEDITOR_ERROR_UNKNOWN,
	NEXVIDEOEDITOR_ERROR_NO_ACTION,
	NEXVIDEOEDITOR_ERROR_INVALID_INFO,
	NEXVIDEOEDITOR_ERROR_INVALID_STATE,
	NEXVIDEOEDITOR_ERROR_VERSION_MISMATCH,
	NEXVIDEOEDITOR_ERROR_CREATE_FAILED,
	NEXVIDEOEDITOR_ERROR_MEMALLOC_FAILED,
	NEXVIDEOEDITOR_ERROR_ARGUMENT_FAILED,
	NEXVIDEOEDITOR_ERROR_NOT_ENOUGH_MEMORY, 		// 10
	NEXVIDEOEDITOR_ERROR_EVENTHANDLER,
	NEXVIDEOEDITOR_ERROR_FILE_IO_FAILED,
	NEXVIDEOEDITOR_ERROR_FILE_INVALID_SYNTAX,
	NEXVIDEOEDITOR_ERROR_FILEREADER_CREATE_FAIL,
	NEXVIDEOEDITOR_ERROR_FILEWRITER_CREATE_FAIL,
	NEXVIDEOEDITOR_ERROR_AUDIORESAMPLER_CREATE_FAIL,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_FORMAT,
	NEXVIDEOEDITOR_ERROR_FILEREADER_FAILED,
	NEXVIDEOEDITOR_ERROR_PLAYSTART_FAILED,
	NEXVIDEOEDITOR_ERROR_PLAYSTOP_FAILED,			// 20
	NEXVIDEOEDITOR_ERROR_PROJECT_NOT_CREATE,
	NEXVIDEOEDITOR_ERROR_PROJECT_NOT_OPEN,
	NEXVIDEOEDITOR_ERROR_CODEC_INIT,
	NEXVIDEOEDITOR_ERROR_RENDERER_INIT,
	NEXVIDEOEDITOR_ERROR_THEMESET_CREATE_FAIL,
	NEXVIDEOEDITOR_ERROR_ADD_CLIP_FAIL,
	NEXVIDEOEDITOR_ERROR_ENCODE_VIDEO_FAIL,
	NEXVIDEOEDITOR_ERROR_INPROGRESS_GETCLIPINFO,
	NEXVIDEOEDITOR_ERROR_THUMBNAIL_BUSY,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_MIN_DURATION,	// 30
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_MAX_RESOLUTION,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_MIN_RESOLUTION,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_VIDEO_PROFILE,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_VIDEO_LEVEL,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_VIDEO_FPS,
	NEXVIDEOEDITOR_ERROR_TRANSCODING_BUSY,
	NEXVIDEOEDITOR_ERROR_TRANSCODING_NOT_SUPPORTED_FORMAT,
	NEXVIDEOEDITOR_ERROR_TRANSCODING_USER_CANCEL,
	NEXVIDEOEDITOR_ERROR_TRANSCODING_NOT_ENOUGHT_DISK_SPACE,
	NEXVIDEOEDITOR_ERROR_TRANSCODING_CODEC_FAILED,			// 40
	NEXVIDEOEDITOR_ERROR_EXPORT_WRITER_INVAILED_HANDLE,
	NEXVIDEOEDITOR_ERROR_EXPORT_WRITER_INIT_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_WRITER_START_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_AUDIO_DEC_INIT_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_VIDEO_DEC_INIT_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_VIDEO_ENC_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_VIDEO_RENDER_INIT_FAIL,
	NEXVIDEOEDITOR_ERROR_EXPORT_NOT_ENOUGHT_DISK_SPACE,

	NEXVIDEOEDITOR_ERROR_UNSUPPORT_AUDIO_PROFILE,

	NEXVIDEOEDITOR_ERROR_THUMBNAIL_INIT_FAIL,		// 50
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_AUDIO_CODEC,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_VIDEO_CODEC,

	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_FILEREADER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_TOO_SHORT_CONTENTS,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_CODEC_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_CODEC_DECODE_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_RENDER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_WRITER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_WRITER_WRITE_ERROR,
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_GET_INDEX_ERROR,			// 60
	NEXVIDEOEDITOR_ERROR_HIGHLIGHT_USER_CANCEL,

	NEXVIDEOEDITOR_ERROR_BACKGROUND_USER_CANCEL,

	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_CLIPLIST_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_CHECK_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_FILEREADER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_FILEWRITER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_DEC_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_DEC_INIT_SURFACE_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_DEC_DECODE_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_INIT_ERROR,		// 70
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_ENCODE_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_INPUT_SURFACE_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_FUNCTION_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_DSI_DIFF_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_ENC_FRAME_CONVERT_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_RENDER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_WRITER_WRITE_ERROR,
	NEXVIDEOEDITOR_ERROR_DIRECTEXPORT_WRITER_UNKNOWN_ERROR,

	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_USER_CANCEL,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_CLIPLIST_ERROR,		// 80
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_FIND_CLIP_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_FIND_READER_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_VIDEO_RENDERER_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_DEC_INIT_SURFACE_ERROR,

	NEXVIDEOEDITOR_ERROR_HW_NOT_ENOUGH_MEMORY,
	NEXVIDEOEDITOR_ERROR_EXPORT_USER_CANCEL, //yoon

	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_DEC_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_FILEREADER_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_TIME_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_RENDER_INIT_ERROR,			// 90
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_OUTPUTSURFACE_INIT_ERROR,
	NEXVIDEOEDITOR_ERROR_FASTPREVIEW_BUSY,
	NEXVIDEOEDITOR_ERROR_CODEC_DECODE,
	NEXVIDEOEDITOR_ERROR_AUDIO_RENDERER,
	NEXVIDEOEDITOR_ERROR_UNSUPPORT_AUDIO_SAMPLINGRATE , 
	
	NEXVIDEOEDITOR_ERROR_IMAGE_PROCESS	= 0x00001001,

}NEXVIDEOEDITOR_ERROR;

//---------------------------------------------------------------------------
#endif	//  _NEXVIDEOEDITOR_ERROR__H_
