#!/bin/bash

python kedl.py --pack theme_baby/*.xml -k kedlkeys
python kedl.py --pack theme_nature/*.xml -k kedlkeys
python kedl.py --pack themes/basic_*.xml -k kedlkeys
python kedl.py --pack themes/builtin_*.xml -k kedlkeys
python kedl.py --pack themes/fun_*.xml -k kedlkeys
python kedl.py --pack themes/energy_*.xml -k kedlkeys
python kedl.py --pack themes/love_*.xml -k kedlkeys
python kedl.py --pack themes/museum_*.xml -k kedlkeys
python kedl.py --pack themes/onstage_*.xml -k kedlkeys
python kedl.py --pack themes/serene_*.xml -k kedlkeys
python kedl.py --pack themes/snow_*.xml -k kedlkeys
python kedl.py --pack themes/travel_*.xml -k kedlkeys

python kedl.py --index output