source 'https://github.com/KineMasterCorp/NexPods.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EditorDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EditorDemo
  
  pod 'NexEditorEngine'
  # pod 'NexEditorEngine', :path => '../../NexEditor'
  # pod 'NexEditorFramework'
  pod 'NexEditorFramework', :path => '../'
  

  target 'EditorDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EditorDemoUITests' do
    # Pods for testing
  end

end
