# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SimpleEditor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleEditor
  pod 'DKImagePickerController'

  pod 'NexEditorFramework', :path => '../../'
  pod 'AssetReader', :path => '../../NexEditorFramework/AssetReader'
  pod 'NexEditorEngine', :path => '../../submodules/NexEditor'
  pod 'EditorAssets', :path => '../../EditorAssets/clear'

  target 'SimpleEditorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
