source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://gerrit.nexstreaming.com:29418/NexPods'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NERSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NERSample
  #pod 'NexRenderer', '~> 0.10.3'
  pod 'NexRenderer', :path=> '../..'

  target 'NERSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
