# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuickPrototypeVideoPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickPrototypeVideoPlayer
  pod 'NexEditorFramework', :path => '../..'
  pod 'AssetReader', :path => '../../NexEditorFramework/AssetReader'
  pod 'DKImagePickerController', '~> 3.8.1'

  target 'QuickPrototypeVideoPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
