source 'https://github.com/KineMasterCorp/NexPods.git'
platform :ios, '9.0'

target 'EditorTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EditorTester
  pod 'NexEditorEngine'
  pod 'NexEditorFramework', :path => '../NexEditor_IOS/'

  target 'EditorTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EditorTesterUITests' do
    # Pods for testing
  end

end
