####################################
# define external library version  #
####################################
NEX_CHUNKPARSER_VERSION := v1.3.2
NEX_CODEC_UTILS_VERSION := 
NEX_COMMON_DEF_VERSION := v1.0.3
NEX_DATASTRUCT_VERSION := v1.1.1
NEX_MEDIA_DEF_VERSION := v1.1.2
NEX_TYPE_DEF_VERSION := v1.0.5
NEX_MIXER_VERSION := v1.1.0
NEX_SAL_VERSION := v4.1.2
NEX_RAL_VERSION := v3.2.2
NEX_CAL_VERSION := v4.6.0
NEX_RESAMPLER_VERSION := v1.0.6
NEX_SECURE_WARE_VERSION := 
NEX_SOUND_VERSION := v3.9.18
NEX_UTILS_VERSION := v1.3.1
NEX_FFREADER_VERSION := v2.61.03
NEX_FFSUBTITLE_VERSION := v2.19.1
NEX_FFWRITER_VERSION := v3.19.7
NEX_XMLPARSER_VERSION := v2.4.0
